import logging
from typing import Optional

import requests

from app.config import settings

logger = logging.getLogger(__name__)

_TELEGRAM_API = "https://api.telegram.org/bot{token}/{method}"


def _api_url(method: str) -> str:
    return _TELEGRAM_API.format(token=settings.TELEGRAM_BOT_TOKEN, method=method)


def send_telegram_message(chat_id: str, text: str) -> bool:
    """Send a text message to a Telegram chat. Returns True on success.

    All text passed to this function should be generated by the application
    (not raw user input) to avoid unintended Markdown injection via parse_mode.
    """
    if not settings.TELEGRAM_BOT_TOKEN:
        logger.warning("TELEGRAM_BOT_TOKEN not set. Telegram messaging disabled.")
        return False
    try:
        resp = requests.post(
            _api_url("sendMessage"),
            json={"chat_id": chat_id, "text": text, "parse_mode": "Markdown"},
            timeout=10,
        )
        if resp.ok:
            logger.info("Telegram message sent to chat %s", chat_id)
            return True
        logger.error("Telegram sendMessage failed: %s", resp.text)
        return False
    except Exception as exc:
        logger.error("Failed to send Telegram message to %s: %s", chat_id, exc)
        return False


def get_file_url(file_id: str) -> Optional[str]:
    """Resolve a Telegram file_id to a direct download URL."""
    if not settings.TELEGRAM_BOT_TOKEN:
        return None
    try:
        resp = requests.get(_api_url("getFile"), params={"file_id": file_id}, timeout=10)
        if resp.ok:
            file_path = resp.json()["result"]["file_path"]
            return (
                f"https://api.telegram.org/file/bot{settings.TELEGRAM_BOT_TOKEN}/{file_path}"
            )
    except Exception as exc:
        logger.error("Failed to resolve Telegram file %s: %s", file_id, exc)
    return None


def set_webhook(url: str) -> bool:
    """Register the bot's webhook URL with Telegram."""
    if not settings.TELEGRAM_BOT_TOKEN:
        logger.warning("TELEGRAM_BOT_TOKEN not set. Cannot set Telegram webhook.")
        return False
    try:
        resp = requests.post(
            _api_url("setWebhook"),
            json={"url": url},
            timeout=10,
        )
        ok = resp.ok and resp.json().get("ok", False)
        if ok:
            logger.info("Telegram webhook registered: %s", url)
        else:
            logger.error("Failed to register Telegram webhook: %s", resp.text)
        return ok
    except Exception as exc:
        logger.error("Exception setting Telegram webhook: %s", exc)
        return False


def parse_telegram_update(body: dict) -> dict:
    """Parse a Telegram Update object into a normalised dict."""
    message = body.get("message") or body.get("edited_message") or {}
    sender = message.get("from", {})
    chat = message.get("chat", {})

    # Text may come from a plain text message or a media caption
    text = message.get("text", "") or message.get("caption", "") or ""

    # Collect media file IDs (largest photo, video, or image document)
    media_file_ids: list[str] = []
    if message.get("photo"):
        # Telegram sends multiple resolutions; take the last (largest)
        media_file_ids.append(message["photo"][-1]["file_id"])
    if message.get("video"):
        media_file_ids.append(message["video"]["file_id"])
    if message.get("document"):
        doc = message["document"]
        mime = doc.get("mime_type", "")
        if mime.startswith(("image/", "video/")):
            media_file_ids.append(doc["file_id"])

    return {
        "chat_id": str(chat.get("id", "")),
        "from_id": str(sender.get("id", "")),
        "first_name": sender.get("first_name", "Unknown"),
        "last_name": sender.get("last_name", ""),
        "username": sender.get("username", ""),
        "text": text,
        "media_file_ids": media_file_ids,
        "update_id": body.get("update_id"),
    }
