"""
Zapier Webhook Integration

Posts property listings to Facebook and Instagram via a Zapier "Catch Hook"
trigger.  When ``ZAPIER_WEBHOOK_URL`` is set the bot sends every "Post
Listing" action as a JSON POST to that URL.  Zapier receives the payload and
routes it to Facebook Pages, Instagram for Business, or any other connected
app in the Zap.

Payload sent to Zapier
──────────────────────
All fields are sent as a single JSON object:

    {
        "description":   "Beautiful 3-bedroom home in Ottawa",
        "price":         "$650,000",
        "location":      "Ottawa, ON",
        "bedrooms":      "3",
        "bathrooms":     "2",
        "contact_phone": "613-xxx-xxxx",
        "image_url":     "https://res.cloudinary.com/.../photo.jpg"
    }

``image_url`` is a public Cloudinary URL (populated when CLOUDINARY_* vars are
set).  Map ``image_url`` to the Photo/Media field in your Zapier Instagram /
Facebook actions.

Required .env variable
──────────────────────
ZAPIER_WEBHOOK_URL – The "Catch Hook" URL generated by Zapier.
                     Run ``/zapier`` in Telegram for the full setup guide.
"""
from __future__ import annotations

import logging
from typing import Optional

import requests

import config

logger = logging.getLogger(__name__)


def is_configured() -> bool:
    """Return True if a Zapier webhook URL is set in config."""
    return bool(config.ZAPIER_WEBHOOK_URL)


def is_all_leads_configured() -> bool:
    """Return True if the all-leads Zapier webhook URL is set in config."""
    return bool(config.ZAPIER_ALL_LEADS_WEBHOOK_URL)


def get_all_leads() -> dict:
    """
    Trigger the "all leads" Zapier Catch Hook and return the parsed leads.

    POSTs ``{"action": "get_all_leads"}`` to ``ZAPIER_ALL_LEADS_WEBHOOK_URL``.
    The Zap is expected to respond with a JSON body containing a ``"leads"``
    list of lead objects (each with keys such as ``first_name``, ``last_name``,
    ``email``, ``phone``, ``intent``, ``score``, ``summary``, ``status``).

    Returns
    -------
    dict
        On success: ``{"success": True, "leads": [...]}``
        On failure: ``{"success": False, "error": "..."}``
    """
    if not config.ZAPIER_ALL_LEADS_WEBHOOK_URL:
        return {"success": False, "error": "ZAPIER_ALL_LEADS_WEBHOOK_URL not configured"}

    try:
        resp = requests.post(
            config.ZAPIER_ALL_LEADS_WEBHOOK_URL,
            json={"action": "get_all_leads"},
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json() if resp.content else {}
        leads = data.get("leads", [])
        logger.info("Zapier all-leads hook triggered (status=%s, leads=%d)", resp.status_code, len(leads))
        return {"success": True, "leads": leads}
    except requests.RequestException as exc:
        logger.error("Zapier all-leads webhook failed: %s", exc)
        return {"success": False, "error": str(exc)}
    except ValueError as exc:
        logger.error("Zapier all-leads response is not valid JSON: %s", exc)
        return {"success": False, "error": f"Invalid JSON response: {exc}"}


def post_listing(listing: dict) -> dict:
    """
    Send a structured property listing to the configured Zapier Catch Hook.

    Parameters
    ----------
    listing : dict
        Keys: ``description``, ``price``, ``location``, ``bedrooms``,
        ``bathrooms``, ``contact_phone``, and optionally ``image_url``
        (public Cloudinary URL).

    Returns a dict with ``success`` bool and ``status_code`` or ``error``.
    """
    if not is_configured():
        return {"success": False, "error": "Zapier webhook URL not configured"}

    try:
        resp = requests.post(
            config.ZAPIER_WEBHOOK_URL,
            json=listing,
            timeout=30,
        )
        resp.raise_for_status()
        logger.info("Zapier hook triggered successfully (status=%s)", resp.status_code)
        return {"success": True, "status_code": resp.status_code}
    except requests.RequestException as exc:
        logger.error("Zapier webhook post failed: %s", exc)
        return {"success": False, "error": str(exc)}
