"""
Zapier Webhook Integration

Posts property listings (caption + optional photo) to Facebook and Instagram
via a Zapier "Catch Hook" trigger.

When ``ZAPIER_WEBHOOK_URL`` is set the bot sends every "Post Listing" action
as an HTTP POST to that URL.  Zapier receives the payload and routes it to
Facebook Pages, Instagram for Business, or any other connected app in the Zap.

Payload sent to Zapier
──────────────────────
Text-only post  : JSON body  ``{"caption": "..."}``
Post with image : multipart  ``data={"caption": "..."}`` + ``files={"image": <file>}``

Required .env variable
──────────────────────
ZAPIER_WEBHOOK_URL – The "Catch Hook" URL generated by Zapier.
                     Run ``/zapier`` in Telegram for the full setup guide.
"""
from __future__ import annotations

import logging
import os
from typing import Optional

import requests

import config

logger = logging.getLogger(__name__)


def is_configured() -> bool:
    """Return True if a Zapier webhook URL is set in config."""
    return bool(config.ZAPIER_WEBHOOK_URL)


def post_to_social(
    caption: str,
    image_path: Optional[str] = None,
) -> dict:
    """
    Send a social media post to the configured Zapier Catch Hook.

    Zapier will receive the payload and publish it to Facebook, Instagram,
    or any other apps wired up in the Zap.

    Parameters
    ----------
    caption    : The post caption / description text.
    image_path : Optional local image file path.  When provided the image is
                 attached as a multipart file upload so Zapier can pass it
                 directly to Facebook / Instagram actions.

    Returns a dict with 'success' bool and 'status_code' or 'error'.
    """
    if not is_configured():
        return {"success": False, "error": "Zapier webhook URL not configured"}

    try:
        if image_path and os.path.exists(image_path):
            with open(image_path, "rb") as img:
                resp = requests.post(
                    config.ZAPIER_WEBHOOK_URL,
                    data={"caption": caption},
                    files={"image": (os.path.basename(image_path), img)},
                    timeout=30,
                )
        else:
            resp = requests.post(
                config.ZAPIER_WEBHOOK_URL,
                json={"caption": caption},
                timeout=30,
            )
        resp.raise_for_status()
        logger.info("Zapier hook triggered successfully (status=%s)", resp.status_code)
        return {"success": True, "status_code": resp.status_code}
    except requests.RequestException as exc:
        logger.error("Zapier webhook post failed: %s", exc)
        return {"success": False, "error": str(exc)}
